"use strict";

module.exports = async function(t, { win }) {
    const LOG = win.Logging;
    const LW = win.Linework;

    t.group("logging/api-surface");
    t.ok(LOG, "Logging global is available");
    t.eq(typeof LOG.log, "function", "Logging.log is a function");
    t.eq(typeof LOG.info, "function", "Logging.info is a function");
    t.eq(typeof LOG.warn, "function", "Logging.warn is a function");
    t.eq(typeof LOG.error, "function", "Logging.error is a function");
    t.eq(typeof LOG.debug, "function", "Logging.debug is a function");
    t.eq(typeof LOG.getLogs, "function", "Logging.getLogs is a function");
    t.eq(typeof LOG.clearLogs, "function", "Logging.clearLogs is a function");
    t.eq(typeof LOG.getStats, "function", "Logging.getStats is a function");
    t.eq(typeof LOG.exportLogs, "function", "Logging.exportLogs is a function");
    t.eq(typeof LOG.exportToReportsHub, "function", "Logging.exportToReportsHub is a function");
    t.eq(typeof LOG.subscribe, "function", "Logging.subscribe is a function");

    t.group("logging/lifecycle & filtering");
    LOG.clearLogs();
    t.eq(LOG.getLogs().length, 0, "logs cleared cleanly");

    let subCalls = 0;
    const unsub = LOG.subscribe(entry => {
        subCalls++;
    });

    LOG.info("System startup initialized", { source: "core" });
    LOG.warn("Low memory warning simulated", { source: "engine", memMB: 128 });
    LOG.error("Failed to parse corrupt packet", { source: "network", code: 404 });
    LOG.debug("Trace point reached", { source: "debug" });

    t.gte(subCalls, 4, "subscriber invoked on each log entry");
    if (typeof unsub === "function") unsub();

    const all = LOG.getLogs();
    t.eq(all.length, 4, "4 log entries recorded");

    const errorsOnly = LOG.getLogs({ level: "ERROR" });
    t.eq(errorsOnly.length, 1, "filtered by ERROR level");
    t.eq(errorsOnly[0].message, "Failed to parse corrupt packet", "correct error message");

    const warningsOnly = LOG.getLogs({ level: "WARN" });
    t.eq(warningsOnly.length, 1, "filtered by WARN level");

    const coreOnly = LOG.getLogs({ source: "core" });
    t.eq(coreOnly.length, 1, "filtered by source=core");

    const searchMatch = LOG.getLogs({ search: "corrupt packet" });
    t.eq(searchMatch.length, 1, "real-time search filter matches keyword");

    const stats = LOG.getStats();
    t.eq(stats.total, 4, "stats.total is 4");
    t.eq(stats.errors, 1, "stats.errors is 1");
    t.eq(stats.warnings, 1, "stats.warnings is 1");
    t.eq(stats.info, 1, "stats.info is 1");
    t.eq(stats.debug, 1, "stats.debug is 1");

    t.group("logging/export & reports bridge");
    const txt = LOG.exportLogs("text");
    t.ok(txt.includes("[ERROR] [network] Failed to parse corrupt packet"), "text export includes formatted log entry");

    const json = LOG.exportLogs("json");
    const parsedJson = JSON.parse(json);
    t.eq(parsedJson.length, 4, "json export parsed correctly");

    if (win.Reports && win.Reports.addReport) {
        const rep = LOG.exportToReportsHub();
        t.ok(rep, "exportToReportsHub succeeded");
        t.ok(rep.id, "report has generated id");
        t.eq(rep.type, "system-logs", "report type is system-logs");
    }

    t.group("linework/csv-quoted-and-error-logging");
    LOG.clearLogs();

    // 1. Quoted CSV row with internal commas in description
    const quotedCsv = [
        "101,2000100.00,600100.00,15.5,\"EP B, R10\"",
        "102,2000200.00,600200.00,15.6,\"EP, LINE 2\"",
        "103,2000300.00,600300.00,15.7,\"EP E, ENDSEG\""
    ].join("\n");

    const parsedQuoted = LW.parsePointFile(quotedCsv, "NE");
    t.eq(parsedQuoted.points.length, 3, "3 quoted CSV points parsed");
    t.eq(parsedQuoted.bad.length, 0, "0 bad rows for valid quoted CSV");
    t.eq(parsedQuoted.points[0].desc, "EP B, R10", "quoted commas preserved in description");
    t.eq(parsedQuoted.points[1].desc, "EP, LINE 2", "second quoted description parsed");

    // 2. CSV with Header and Malformed Rows
    const csvWithErrors = [
        "Point,Northing,Easting,Elevation,Description",
        "1,2000000.00,600000.00,10.0,BL B",
        "invalid_row_with_no_coords",
        "2,2000100.00,corrupt_east,10.0,BL",
        "3,2000200.00,600000.00,10.0,BL E"
    ].join("\n");

    const parsedErrors = LW.parsePointFile(csvWithErrors, "NE");
    t.eq(parsedErrors.points.length, 2, "2 valid point rows parsed");
    t.gte(parsedErrors.bad.length, 2, "2 malformed rows recorded in bad array");
    t.ok(parsedErrors.badDetails && parsedErrors.badDetails.length >= 2, "badDetails contains diagnostic objects");
    t.eq(parsedErrors.stats.headerDetected, "Point,Northing,Easting,Elevation,Description", "header row detected");

    // 3. Verify logging events were generated by Linework import
    const lineworkLogs = LOG.getLogs({ source: "linework" });
    t.gte(lineworkLogs.length, 2, "Linework parser dispatched diagnostic logs to Logging plugin");
    const warnLogs = lineworkLogs.filter(l => l.level === "WARN");
    t.gte(warnLogs.length, 2, "Linework parser logged warnings for skipped rows");
};
