/**
 * Plugin: plat2dxf (Parcel → DXF / Points / COGO)
 * plugins/plat2dxf/plat2dxf.js
 *
 * The "Plat-to-DXF" tab was a static mockup — the buttons did nothing and there
 * is no image tracing in this build. This plugin makes the tab do real work: it
 * turns a bearing/distance call list (or a bundled sample parcel) into a valid
 * ASCII DXF, a P,N,E,Z,D point file, and an AutoCAD COGO (.scr) script, all via
 * core/cogo.js. No computer vision — the UI is relabelled to say so.
 *
 * Registers via window.PluginRegistry. Depends on core/cogo.js.
 */
(function () {
    "use strict";

    const MANIFEST = {
        name: "plat2dxf",
        version: "1.0.0",
        description: "Bearing/distance call list (or sample parcel) -> valid ASCII DXF, P,N,E,Z,D point file, and AutoCAD COGO script.",
        tab: "tab-plat2dxf",
        icon: "fa-wand-magic-sparkles",
        tier: "Pro",
        dependencies: []
    };

    // A real, closing FDOT-style parcel used when no call list is supplied.
    const SAMPLE_CALLS = [
        "N 89-58-12 E 320.44",
        "S 00-14-03 E 210.88",
        "S 89-58-12 W 320.44",
        "N 00-14-03 W 210.88"
    ];

    let _last = null;

    function parseCalls(text) {
        const lines = (text || "").split(/\r?\n/).map(s => s.trim()).filter(Boolean);
        const src = lines.length ? lines : SAMPLE_CALLS;
        const legs = [];
        const bad = [];
        src.forEach((line, i) => {
            const b = window.COGO.parseBearing(line);
            const d = line.match(/([\d,]+(?:\.\d+)?)\s*(?:feet|foot|ft|')?\s*$/i);
            if (b && d) legs.push({ azimuthDeg: b.azimuthDeg, distance: parseFloat(d[1].replace(/,/g, "")), kind: "line", raw: line });
            else bad.push(`Line ${i + 1}: "${line}"`);
        });
        return { legs, bad, usedSample: !lines.length };
    }

    function build(text) {
        const { legs, bad, usedSample } = parseCalls(text);
        if (legs.length < 3) return { error: "Need at least 3 valid bearing/distance calls.", bad };
        const tr = window.COGO.runTraverse(legs);
        // vertices minus the duplicated closing point
        const verts = tr.vertices.slice(0, -1);
        return { legs, bad, usedSample, traverse: tr, verts };
    }

    function toDxf(r) {
        const verts = r.verts;
        const texts = [];
        r.legs.forEach((leg, i) => {
            const a = verts[i], b = verts[(i + 1) % verts.length];
            texts.push({
                layer: "AI-NODE-TEXT",
                e: (a.e + b.e) / 2, n: (a.n + b.n) / 2, height: 4,
                value: `${window.COGO.azimuthToBearing(leg.azimuthDeg)}  ${leg.distance.toFixed(2)}'`
            });
        });
        verts.forEach((v, i) => texts.push({ layer: "AI-NODE-TEXT", e: v.e, n: v.n, height: 3, value: i === 0 ? "POB" : `P${i}` }));
        return window.COGO.buildDxf({
            layers: [{ name: "AI-PROP-BNDY", color: 4 }, { name: "AI-NODE-TEXT", color: 2 }],
            polylines: [{ layer: "AI-PROP-BNDY", closed: true, points: verts }],
            texts
        });
    }

    function toCogoScript(r) {
        const L = [];
        L.push("; AutoCAD COGO line script — generated by FDOT Civil3D Standards (plat2dxf)");
        L.push("; Draws the parcel boundary from bearing/distance calls. Run with SCRIPT.");
        L.push("_.-LAYER _Make AI-PROP-BNDY _Color 4 AI-PROP-BNDY \"\" _Exit");
        L.push("_.PLINE");
        L.push("0,0");
        let cur = { e: 0, n: 0 };
        r.legs.forEach(leg => {
            cur = window.COGO.advance(cur, leg.azimuthDeg, leg.distance);
            L.push(`${cur.e.toFixed(4)},${cur.n.toFixed(4)}`);
        });
        L.push("_Close");
        L.push("_.ZOOM _Extents");
        return L.join("\r\n") + "\r\n";
    }

    function render(ctx) {
        const box = document.getElementById("plat-tracing-preview");
        const out = document.getElementById("plat2dxf-summary");
        const r = build(document.getElementById("plat2dxf-input")?.value || "");
        _last = r;

        if (r.error) {
            if (out) window.setSafeHTML(out, `<div style="color:var(--danger);"><i class="fa-solid fa-triangle-exclamation"></i> ${r.error}${r.bad && r.bad.length ? "<br>Unparsed: " + r.bad.join("; ") : ""}</div>`);
            if (box) box.classList.remove("hidden");
            return;
        }

        const t = r.traverse;
        if (box) box.classList.remove("hidden");
        if (out) {
            window.setSafeHTML(out, `
                <div style="font-size:0.85rem;">
                  ${r.usedSample ? '<div style="color:var(--text-muted); margin-bottom:0.4rem;"><i class="fa-solid fa-circle-info"></i> No calls entered — using the bundled sample parcel.</div>' : ''}
                  ${r.bad && r.bad.length ? `<div style="color:var(--warning);">Skipped ${r.bad.length} unparsed line(s): ${r.bad.join("; ")}</div>` : ''}
                  <strong>${r.legs.length} courses</strong> ·
                  perimeter <strong>${t.perimeter.toFixed(2)} ft</strong> ·
                  area <strong>${t.areaAcres.toFixed(3)} ac</strong> ·
                  misclosure <strong>${t.misclosure.toFixed(3)} ft</strong>
                  (${t.precisionDenominator === Infinity ? "exact" : "1:" + Math.round(t.precisionDenominator).toLocaleString()})
                </div>`);
        }
        if (ctx) ctx.showToast(`Parcel ready: ${r.legs.length} courses, ${r.traverse.areaAcres.toFixed(2)} ac.`);
    }

    const Plugin = {
        init() {
            // Relabel the mockup so it stops claiming image computer-vision.
            const card = document.querySelector("#tab-plat2dxf .qc-checklist-card");
            const h2 = card && card.querySelector("h2");
            const sub = card && card.querySelector("p.subtitle");
            if (h2) window.setSafeHTML(h2, `<i class="fa-solid fa-wand-magic-sparkles"></i> Parcel → DXF / Points / COGO Script`);
            if (sub) sub.textContent = "Enter a bearing/distance call list (or use the bundled sample). Produces a valid ASCII DXF, a P,N,E,Z,D point file, and an AutoCAD COGO script. No image tracing in this build.";

            // Insert an input box above the dropzone mockup if not already there.
            const dz = card && card.querySelector('div[style*="dashed"]');
            if (dz && !document.getElementById("plat2dxf-input")) {
                const wrap = document.createElement("div");
                wrap.className = "form-group";
                wrap.style.marginTop = "1rem";
                window.setSafeHTML(wrap, `
                    <label for="plat2dxf-input">Bearing / distance calls (one per line, e.g. <code>N 45-12-30 E 150.00</code>)</label>
                    <textarea id="plat2dxf-input" rows="5" style="width:100%; box-sizing:border-box; font-family:var(--font-mono); font-size:0.8rem;"></textarea>`);
                dz.parentNode.insertBefore(wrap, dz);
                const btn = document.getElementById("btn-sim-upload");
                if (btn) window.setSafeHTML(btn, `<i class="fa-solid fa-gears"></i> Build Parcel DXF / Points`);
            }
            const summary = document.createElement("div");
            summary.id = "plat2dxf-summary";
            summary.style.marginTop = "0.75rem";
            const preview = document.getElementById("plat-tracing-preview");
            if (preview && !document.getElementById("plat2dxf-summary")) preview.appendChild(summary);
        },

        setupEvents(ctx) {
            document.getElementById("btn-sim-upload")?.addEventListener("click", () => render(ctx));
            document.getElementById("btn-download-dxf")?.addEventListener("click", () => {
                if (!_last || _last.error) { render(ctx); if (!_last || _last.error) return; }
                window.COGO.downloadText("parcel_boundary.dxf", toDxf(_last), "application/dxf");
                ctx.showToast("Downloaded parcel_boundary.dxf");
            });
            document.getElementById("btn-download-txt")?.addEventListener("click", () => {
                if (!_last || _last.error) { render(ctx); if (!_last || _last.error) return; }
                window.COGO.downloadText("parcel_coordinates.txt", window.COGO.pnezd(_last.verts), "text/csv");
                ctx.showToast("Downloaded parcel_coordinates.txt");
            });
            document.getElementById("btn-download-cogo")?.addEventListener("click", () => {
                if (!_last || _last.error) { render(ctx); if (!_last || _last.error) return; }
                window.COGO.downloadText("parcel_cogo.scr", toCogoScript(_last));
                ctx.showToast("Downloaded parcel_cogo.scr");
            });
        }
    };

    if (window.PluginRegistry) window.PluginRegistry.register(MANIFEST, Plugin);
})();
